Implement Category Entity and Associated Functionality
MateuszRostek/book-store pull request #10
Opened 2024-03-13 14:53 UTC by MateuszRostek

Introduction of Category entity with id, name, and description attributes.
Addition of a private Set<Category> field in the Book class for the relationship.
Implementation of CategoryRepository for CRUD operations using JpaRepository.
Development of DTO classes for seamless data transfer.
Expansion of BookMapper and introduction of CategoryMapper for mapping entities to DTOs.
Implementation of CategoryService with CRUD operations in CategoryServiceImpl.
Creation of CategoryController with endpoints for CRUD operations.
Integration of Pagination, Sorting, and Swagger documentation for enhanced API usability.
Implementation of soft delete and using Liquibase for maintaining data integrity.

2024-03-14 14:02 UTC, nowickimj requested changes
I've encountered problems while testing your code - here's the case scenario:
1. I've registered a new user (id = 3):
![obraz](https://github.com/MateuszRostek/book-store/assets/19765018/6d6ade76-2e99-4f73-b3f5-f535bcab7654)
2. I've granted user #3 an ADMIN role:
![obraz](https://github.com/MateuszRostek/book-store/assets/19765018/10546706-835a-4ca9-9aeb-8611c16c5435)
3. I use API to log in and get the bearer token.
4. GET on /api/categories works but when I try to call POST to create a new category, I got 401.

Please verify if your security configuration is correct.

2024-03-14 14:02 UTC, nowickimj commented on src/main/java/book/store/service/user/impl/UserServiceImpl.java
> +        modelUser.setRoles(roles);
You can simplify such usages with `modelUser.setRoles(Set.of(defaultRole));

2024-03-14 15:19 UTC, MateuszRostek commented
I can't recreate the problem you have, here is a video, it works fine for me:
https://www.loom.com/share/39024ff4dde74c9697f97bb905d5bc01?sid=f9ce00bb-cbf8-4cdd-a065-ab23a37d9579

2024-03-15 11:51 UTC, nowickimj approved these changes

2024-03-15 12:27 UTC, merged

2024-08-03 07:45 UTC, MateuszRostek reviewed
.